# Generated by Django 5.1.4 on 2025-01-06 11:22

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStrEnumProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', django_enum.fields.EnumCharField(choices=[('E', 'Electronics'), ('C', 'Clothing'), ('B', 'Books'), ('F', 'Food')], default='E', max_length=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['E', 'C', 'B', 'F'])), name='core_ProductStrEnumProp_category_CategoryStrEnumProp')],
            },
        ),
        migrations.CreateModel(
            name='ProductTextChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', django_enum.fields.EnumCharField(choices=[('E', 'Electronics'), ('C', 'Clothing'), ('B', 'Books'), ('F', 'Food')], default='E', max_length=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['E', 'C', 'B', 'F'])), name='core_ProductTextChoices_category_CategoryTextChoices')],
            },
        ),
    ]
